include: package:lint/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude: 
    - 'constants/**'


dart_code_metrics:
  rules:
    - newline-before-return:
        severity: error
    - arguments-ordering:
        severity: error
    - avoid-collection-methods-with-unrelated-types:
        severity: error
    - avoid-double-slash-imports:
        severity: error
    - avoid-duplicate-exports:
        severity: error
    - avoid-dynamic:
        severity: error
    - avoid-global-state:
        severity: error
    - avoid-ignoring-return-values:
        severity: error
    - avoid-late-keyword:
        severity: error
    - avoid-missing-enum-constant-in-map:
        severity: error
    - avoid-nested-conditional-expressions:
        severity: error
    - avoid-non-null-assertion:
        severity: error
    - avoid-passing-async-when-sync-expected:
        severity: error
    - avoid-redundant-async:
        severity: error
    - avoid-throw-in-catch-block:
        severity: error
    - avoid-unnecessary-conditionals:
        severity: error
    - avoid-unnecessary-type-assertions:
        severity: error
    - avoid-unnecessary-type-casts:
        severity: error
    - avoid-unrelated-type-assertions:
        severity: error
    - avoid-unused-parameters:
        severity: error
    - binary-expression-operand-order:
        severity: error
    - format-comment:
        severity: error
    - list-all-equatable-fields:
        severity: error
    - member-ordering:
        severity: error
    - no-boolean-literal-compare:
        severity: error
    - no-empty-block:
        severity: error
    - no-equal-arguments:
        severity: error
    - no-equal-then-else:
        severity: error
    - no-magic-number:
        severity: error
    - prefer-conditional-expressions:
        severity: error
    - prefer-correct-test-file-name:
        severity: error
    - prefer-correct-type-name:
        severity: error
    - prefer-enums-by-name:
        severity: error
    - prefer-immediate-return:
        severity: error
    - prefer-iterable-of:
        severity: error
    - prefer-match-file-name:
        severity: error
    - prefer-moving-to-variable:
        severity: error
    - prefer-static-class:
        severity: error
    - prefer-trailing-comma:
        severity: error
    - always-remove-listener:
        severity: error
    - avoid-border-all:
        severity: error
    - avoid-expanded-as-spacer:
        severity: error
    - avoid-returning-widgets:
        severity: error
    - avoid-shrink-wrap-in-lists:
        severity: error
    - avoid-wrapping-in-padding:
        severity: error
    - prefer-const-border-radius:
        severity: error
    - prefer-correct-edge-insets-constructor:
        severity: error
    - prefer-define-hero-tag:
        severity: error
    - prefer-extracting-callbacks:
        severity: error
    - prefer-single-widget-per-file:
        severity: error
    - prefer-using-list-view:
        severity: error

  metrics:
    cyclomatic-complexity: 6
    lines-of-code: 100
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50

