name: ditto
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  provider:
  web_socket_channel:
  logger:
  google_fonts: ^4.0.3
  crypto:
  sqlite3_flutter_libs:
  sqlite3:
  path_provider:
  progress_indicators:
  flutter_bloc:
  flutter_remix:
  hive_flutter:
  equatable:
  dart_nostr:
    git: https://github.com/anasfik/nostr.git

  convert:

  image_picker:
  cached_network_image:
  http: ^0.13.5
  timeago: ^3.4.0
  dart_openai: ^1.9.1
  hashtagable: ^2.1.0
  transitioned_indexed_stack: ^1.0.2
  flutter_islamic_icons: ^1.0.2
  process_run: ^0.12.5+3
  flutter_animate: ^4.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics:

  flutter_lints:

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
