name: ditto
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+9

environment:
  sdk: ">=3.0.0 <3.9.9"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0

  cupertino_icons:
  provider:
  # web_socket_channel:
  # logger:
  google_fonts:
  crypto:
  # sqlite3_flutter_libs:
  # sqlite3:
  path_provider: ^2.1.2
  progress_indicators:
  flutter_bloc:
  flutter_remix:
  hive_flutter:
  equatable:
  dart_nostr: ^6.0.2
  convert:
  image_picker:
  cached_network_image:
  http:
  timeago:
  easy_localization:
  dart_openai: ^1.9.1
  hashtagable_v3:
  transitioned_indexed_stack:
  flutter_islamic_icons:
  # process_run: ^0.12.5+3
  flutter_animate:
  envied:
  youtube_player_flutter:
  device_preview:
  # flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html:
  flutter_svg: ^2.0.5
  hex: ^0.2.0
  kepler: ^1.0.3
  sec: ^1.1.0
  pointycastle: ^3.7.3
  bip39: ^1.0.6
  flutter_tts: ^3.8.5
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.7.2
  # flutter_launcher_icons: ^0.13.1
  # flutter_app_name:
  # change_app_package_name: ^1.1.0

  # flutter_lints:
  # build_runner: ^2.3.3
  # envied_generator: ^0.3.0
  # flutter_native_splash: ^2.2.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/logo/icon_rounded.png"
  image_path_ios: "assets/logo/icon_rounded.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/logo/
    - assets/translations/

flutter_app_name:
  name: "Al Ittihad"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo/logo_no_bg_splash.png"

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. It is supported for Android, iOS and the Web.  For Android 12,
  # see the Android 12 section below.
  #branding: assets/dart.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  color_dark: "#000000"

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    color: "#ffffff"
    color_dark: "#000000"

    # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
    # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
    # do not remove any spaces:
    #info_plist_files:
    #  - 'ios/Runner/Info-Debug.plist'
    #  - 'ios/Runner/Info-Release.plist'
