name: chat_gpt_sdk
description: create chat bot and other bot with ChatGPT SDK
version: 2.0.4
homepage: https://www.facebook.com/REDEVRX
repository: https://github.com/redevRx/Flutter-ChatGPT

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter:

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.1
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
